
services:
  database:
    container_name: database
    image: postgres
    restart: always
    ports:
      - 5432:5432    
    environment:
    - POSTGRES_PASSWORD=example
    - POSTGRES_USER=lean
    - POSTGRES_DB=App

  adminer:
    image: adminer
    restart: always
    ports:
      - 2000:2000
